sibling of b9da54e56144d9a2f06babc6e340ff46bc3b0510

diff --git a/test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/02-create-task.yaml b/test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/02-create-task.yaml
--- a/test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/02-create-task.yaml
+++ b/test/conformance/kuttl/verifyImages/clusterpolicy/standard/imageExtractors-simple/02-create-task.yaml
@@ -1,5 +1,14 @@
+## Checks that the manifests.yaml file CANNOT be successfully created. If it can, fail the test as this is incorrect.
+
 apiVersion: kuttl.dev/v1beta1
 kind: TestStep
-apply:
-- file: badtask.yaml
-  shouldFail: true
+commands:
+- script: |
+    if kubectl apply -f badtask.yaml
+    then 
+      echo "Tested failed. Task was created when it shouldn't have been."
+      exit 1 
+    else 
+      echo "Test succeeded. Task was not created as intended."
+      exit 0
+    fi
diff --git a/test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/03-create-bad-pod.yaml b/test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/03-create-bad-pod.yaml
--- a/test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/03-create-bad-pod.yaml
+++ b/test/conformance/kuttl/verifyImages/clusterpolicy/standard/noconfigmap-diffimage-success/03-create-bad-pod.yaml
@@ -1,5 +1,12 @@
 apiVersion: kuttl.dev/v1beta1
 kind: TestStep
-apply:
-- file: bad-pod.yaml
-  shouldFail: true
+commands:
+- script: |
+    if kubectl apply -f bad-pod.yaml
+    then 
+      echo "Tested failed. Pod was created when it shouldn't have been."
+      exit 1 
+    else 
+      echo "Test succeeded. Pod was not created as intended."
+      exit 0
+    fi
diff --git a/test/conformance/kuttl/verifyImages/clusterpolicy/standard/nomutateDigest-verifyDigest-norequired/04-create-badpod.yaml b/test/conformance/kuttl/verifyImages/clusterpolicy/standard/nomutateDigest-verifyDigest-norequired/04-create-badpod.yaml
--- a/test/conformance/kuttl/verifyImages/clusterpolicy/standard/nomutateDigest-verifyDigest-norequired/04-create-badpod.yaml
+++ b/test/conformance/kuttl/verifyImages/clusterpolicy/standard/nomutateDigest-verifyDigest-norequired/04-create-badpod.yaml
@@ -2,6 +2,13 @@
 
 apiVersion: kuttl.dev/v1beta1
 kind: TestStep
-apply:
-- file: badpod.yaml
-  shouldFail: true
+commands:
+- script: |
+    if kubectl apply -f badpod.yaml
+    then 
+      echo "Tested failed. Bad pod was created when it shouldn't have been."
+      exit 1 
+    else 
+      echo "Test succeeded. Bad pod was not created as intended."
+      exit 0
+    fi
